version: "3.9"  # optional since v1.27.0
services:
  product-service:
    image: vadudduk/jenkinssb
    container_name: jenkinssb
    build:
      context: ./build/libs
      args:
        - APP_NAME=jenkins
        - APP_VERSION=0.0.1
    environment:
      SPRING_PROFILES_ACTIVE: dev
      
    expose:
      - 8081
    ports:
      - 8081:8081